import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6112+xS9DPL._AC_UL320_.jpg",
    title: "Nike AirForce", 
    newPrice: "$ 200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51574uG5mPL._AC_SL1200_.jpg",
    title: "Nike AirMax 90", 
    newPrice: "$200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71lrjOUqXKL._AC_SL1500_.jpg",
    title: "Nike Sacai",
    newPrice: "$200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/31dLl4F5YbL._AC_.jpg",
    title: "Runfalcon",
    newPrice: "$200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/813p+UUmv9L._AC_SL1500_.jpg",
    title: "Brown Flats",
    newPrice: "$200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    newPrice: "$50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    newPrice: "$50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71Tb00rLtYL._AC_SL1500_.jpg",
    title: "Samba OG",
    newPrice: "$200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71NphOvJUwL._AC_SL1500_.jpg",
    title: "SB Dunk Low",
    newPrice: "$200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/511WMwg9vGL._AC_SL1500_.jpg",
    title: "Puma Duramo",
    newPrice: "$150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51GE1glhUeL._AC_SL1200_.jpg",
    title: "Skyview",
    newPrice: "$150",
    company: "Puma",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/715bTH5g0hL._AC_SL1500_.jpg",
    title: "Wallabees", 
    newPrice: "$150",
    company: "Puma",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker", 
    newPrice: "$150",
    company: "Puma",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit", 
    newPrice: "$150",
    company: "Puma", 
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/715fYHhRejL._AC_SL1500_.jpg",
    title: "Jordan 4",
    newPrice: "$150",
    company: "Nike",  
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/416KDkASlqL._AC_.jpg",
    title: "Bage Flats",  
    newPrice: "$100",
    company: "Vans",  
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/719ZybK3SDL._AC_SL1500_.jpg",
    title: "Tecs", 
    newPrice: "$100",
    company: "Vans",  
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61OcIUw4fAL._AC_SL1200_.jpg",
    title: "Birkenstock",   
    newPrice: "$100",
    company: "Vans",   
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/415P3QftiRL._AC_.jpg",
    title: "Sketchers",   
    newPrice: "$50",
    company: "Nike",   
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",  
    newPrice: "$50",
    company: "Vans",  
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",  
    newPrice: "$100",
    company: "puma",   
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    newPrice: "$150",
    company: "Nike",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Eu6wu0-GL._AC_SL1000_.jpg",
    title: "Converse",
    newPrice: "$200",
    company: "Nike", 
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    newPrice: "$200",
    company: "Nike",  
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel", 
    newPrice: "$50",
    company: "Adidas", 
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",  
    newPrice: "$150",
    company: "Adidas",  
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",   
    newPrice: "$50",
    company: "Adidas",  
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61A4QcPScOL._AC_SL1500_.jpg",
    title: "Doll shoes",   
    newPrice: "$50",
    company: "Adidas",
    category: "flats",
  },
];

export default data;
